name: conduit_open_api_forked
version: 1.0.1
homepage: https://github.com/feedmepos/open-api-dart
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications. Fork, with discriminator support.
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  conduit_codable: ^1.0.0-0
  meta: ^1.1.5
dev_dependencies:
  dcli: ^1.0.0
  lint: ^1.5.3
  test: ^1.3.0
